services:

  # Applications
  # Compiled
  c:
    build: ./templates/application/compiled/c/static
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true
  gtk:
    build: ./templates/application/compiled/c/gtk
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  csharp:
    build: ./templates/application/compiled/csharp/static
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true
  dotnet:
    build: ./templates/application/compiled/csharp/dotnet
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  cpp:
    build: ./templates/application/compiled/cpp
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true
  
  go:
    build: ./templates/application/compiled/go
    volumes:
      - ${PROJECT_PATH}:/app
    environment:
      - PROJECT_ID=${PROJECT_ID}
    stdin_open: true
    tty: true

  java:
    build: ./templates/application/compiled/java/static
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  rust:
    build: ./templates/application/compiled/rust
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  hadoop:
    build: ./templates/application/compiled/java/hadoop
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  swift:
    build: ./templates/application/compiled/swift
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  # Interpreted
  bash:
    build: ./templates/application/interpreted/bash
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  batch:
    build: ./templates/application/interpreted/batch
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  lua:
    build: ./templates/application/interpreted/lua
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  perl:
    build: ./templates/application/interpreted/perl
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  powershell:
    build: ./templates/application/interpreted/powershell
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  python:
    build: ./templates/application/interpreted/python
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  ruby:
    build: ./templates/application/interpreted/ruby
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  # Data Formats
  json:
    build: ./templates/dataformat/json
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  xml:
    build: ./templates/dataformat/xml
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  yaml:
    build: ./templates/dataformat/yaml
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  # Websites
  # Backend
  aspnet:
    build: ./templates/website/backend/aspnet
    ports:
      - "8080:80"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  django:
    build: ./templates/website/backend/django
    ports:
      - "8000:8000"
    volumes:
      - ${PROJECT_PATH}:/app
    environment:
      - PROJECT_ID=${PROJECT_ID}
    stdin_open: true
    tty: true

  express:
    build: ./templates/website/backend/express
    ports:
      - "3000:3000"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  fastapi:
    build: ./templates/website/backend/fastapi
    ports:
      - "8000:8000"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  flask:
    build: ./templates/website/backend/flask
    ports:
      - "5000:5000"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  rails:
    build: ./templates/website/backend/rails
    ports:
      - "3000:3000"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  springboot:
    build: ./templates/website/backend/springboot
    ports:
      - "8080:80"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  # Frontend

  angular:
    build: ./templates/website/frontend/angular
    ports:
      - "8080:80"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  nginx:
    build: ./templates/website/frontend/html/nginx
    ports:
      - "8080:80"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true
  apache:
    build: ./templates/website/frontend/html/apache
    ports:
      - "8080:80"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  react:
    build: ./templates/website/frontend/react
    ports:
      - "3000:3000"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  vue:
    build: ./templates/website/frontend/vue
    ports:
      - "3000:3000"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  # Fullstack

  laravel:
    build: ./templates/website/fullstack/laravel
    ports:
      - "8000:8000"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true

  nextjs:
    build: ./templates/website/fullstack/nextjs
    ports:
      - "3000:3000"
    volumes:
      - ${PROJECT_PATH}:/app
    stdin_open: true
    tty: true